name: appointnew
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.8.0

dev_dependencies:
  fake_cloud_firestore: ^1.3.0

flutter:
  uses-material-design: true
